#tomcat端口号
server:
  port: 8081

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa_office?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
