#tomcat端口号
server:
  port: 8081

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa_office?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
# FastDFS-Client 配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list:
    - 192.168.163.111:22122
  thumb-image:
    height: 200
    width: 200
